name: Secret varibales

on: workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Printing Secret Variables
              run: |
               echo "SECRET VARIABLE"
               echo "${{secrets.MY_SEC}}"