name: Custom Python Action Workflow

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Custom Python Action
        uses: ./.github/actions/custom-action1
        with:
          message: "Hello from workflow"
