name: Artifacts with view

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir -p build
          echo "Hellooooo" > build/output.txt
          # Debug: List files in build directory
          ls -la build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/output.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: List downloaded files
        run: ls -la build

      - name: Use
        run: cat build/output.txt
